#include "sample_module.h"

/* dfadsf
fadsf
fsd
*/

//{oneway}RetType{typedes} function_name(ParamType{typedes} ParamName,ParamType*{typedes}{inout}{Count} ParamName)

{oneway}const char* sample_ptr_api(ParamType{typedes1} ParamName,ParamType*{typedes2}{inout}{*} ParamName);


{oneway}const int32_t* sample_ptr_api1();


{oneway}const int32_t* sample_ptr_api2(void);


int32_t{int32} sample_base_api1(int32_t{int32} in,int32_t*{int32}{inout}{1} out);

int sample_base_api(int in,int* out);

const char* sample_ptr_api(char* in,char*{input}{*} out,int outlen);

SAMPLE_ST*{struct} sample_st_api(SAMPLE_ST*{struct} in, SAMPLE_ST*{struct}{inout}{1} out);

{oneway}void sample_void_api(int in);




//const char* sample_ptr_api(char* in,char*{input}{*} out,int outlen);
